### ISSUE TITLE
Regex does not work for all embed types

### ISSUE THREAD

**Issue by carolineboeykens** [statikbe/craft-video-parser#3]
We're having issues with some URL's in the video embed:

This does not work:
https://www.youtube-nocookie.com/embed/zwzCwQM86JA

It looks like this changed when the "shorts" option was added:
Example: https://www.youtube.com/shorts/jtnOo-DAYWk

The error we get is:
<img width="1406" alt="Screenshot 2023-05-02 at 11 56 37" src="https://user-images.githubusercontent.com/42932673/235636886-a8b7d417-c4d8-49e8-ab41-fd3dbf7ee455.png">

**Comment by HannahDeWachter** [comment]
Try to include this in the Unit Tests

**Comment by janhenckens** [comment]
I think we have this working in the meantime - and it's covered in [this test](https://github.com/statikbe/craft-video-parser/blob/main/tests/unit/VideoUrlUnitTest.php#L41).

Testing it in a template also returns the correct embed.
